import type { Metadata } from 'next';
import { Geist, Geist_Mono, Courier_Prime } from 'next/font/google';
import './globals.css';
import { DialogProvider } from '@/providers/dialog-provider';
import { Toaster } from 'react-hot-toast';
import { DataProvider } from '@/providers/data-provider';

const geistSans = Courier_Prime({
    variable: '--font-geist-sans',
    subsets: ['latin'],
    weight: '400',
});

const geistMono = Courier_Prime({
    variable: '--font-geist-mono',
    subsets: ['latin'],
    weight: '400',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <Toaster />
                <main className="px-4">
                    <section className="max-w-[1440px] mx-auto">
                        <DataProvider>
                            <DialogProvider>{children}</DialogProvider>
                        </DataProvider>
                    </section>
                </main>
            </body>
        </html>
    );
}
